In [5]:
import numpy as np
import random
import imageio


In [95]:
#parametros que na entrega devem ser lidos do stdin
#gera a imagem 1
C = 512
Q = 1
F = 2
N = 256
B = 4
S = 1

In [100]:
#gera imagem 2
C = 512
Q = 2
F = 32
N = 256
B = 6
S = 1


In [103]:
#gera imagem 3
C = 512
Q = 1001
#F = 32
N = 256
B = 3
S = 1

1

In [96]:
#setting rand seed
random.seed(S)

In [65]:
def normalize(matrix, start, end):
    return (matrix - matrix.min())/(matrix.max() - matrix.min()) * (end-start) + start

In [ ]:
def downsampling(matrix, N):
    return matrix[0::N,0::N]

In [93]:
def downsampling_quatification(matrix, N, B):
    m_normalized = normalize(matrix, 0, 255)
    m_normalized = m_normalized.astype(np.uint8)
    r_shift = np.right_shift(m_normalized, B)
    return np.left_shift(r_shift, B)

In [30]:
#
def func1(C):
    return np.fromfunction(lambda x,y: ((x*y)+ 2*y), (C, C))

In [35]:
def func2(C, Q):
    return np.fromfunction(lambda x,y,Q: np.absolute(((np.cos(x/Q))+ (2*np.sin(y/Q)))), (C, C), Q = Q)

In [41]:
def func3(C, Q):
    return np.fromfunction(lambda x,y,Q: np.absolute(((3*(x/Q)) - (np.power((y/Q),(1/3))))), (C, C), Q = Q)

In [59]:
teste = func3(C, Q)
teste

array([[0.        , 1.        , 1.25992105, 1.44224957],
       [3.        , 2.        , 1.74007895, 1.55775043],
       [6.        , 5.        , 4.74007895, 4.55775043],
       [9.        , 8.        , 7.74007895, 7.55775043]])

In [64]:
normalize(teste, 0, 65535)

array([[    0.        ,  7281.66666667,  9174.32511165, 10501.98062112],
       [21845.        , 14563.33333333, 12670.67488835, 11343.01937888],
       [43690.        , 36408.33333333, 34515.67488835, 33188.01937888],
       [65535.        , 58253.33333333, 56360.67488835, 55033.01937888]])

In [105]:
m = func1(C)
m = normalize(m, 0, 65535)
result = downsampling_quatification(m, N, B)
imageio.imwrite('image_1.png', result)
result

array([[  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0],
       ...,
       [  0,   0,   0, ..., 248, 248, 248],
       [  0,   0,   0, ..., 248, 248, 248],
       [  0,   0,   0, ..., 248, 248, 248]], dtype=uint8)

In [101]:
m = func2(C, Q)
m = normalize(m, 0, 65535)
result = downsampling_quatification(m, N, B)
imageio.imwrite('image_2.png', result)
result

array([[ 64, 128, 192, ...,  64,   0,   0],
       [ 64, 128, 192, ...,  64,   0,  64],
       [  0,  64, 128, ...,   0,   0,  64],
       ...,
       [ 64,   0,   0, ...,  64, 128, 192],
       [ 64,   0,  64, ...,  64, 128, 192],
       [  0,   0,  64, ...,   0, 128, 128]], dtype=uint8)

In [104]:
m = func3(C, Q)
m = normalize(m, 0, 65535)
result = downsampling_quatification(m, N, B)
imageio.imwrite('image_3.png', result)
result

array([[  0,  16,  16, ..., 128, 128, 128],
       [  0,  16,  16, ..., 128, 128, 128],
       [  0,   8,  16, ..., 128, 128, 128],
       ...,
       [248, 232, 232, ..., 120, 120, 120],
       [248, 232, 232, ..., 120, 120, 120],
       [248, 232, 232, ..., 120, 120, 120]], dtype=uint8)